# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: friendList
  username: root
  password: resa884a
  host: localhost

development:
  <<: *default
  adapter: postgresql
  database: friendList
  username: root
  password: resa884a
  host: localhost

test:
  <<: *default
  adapter: postgresql
  database: friendList
  username: root
  password: resa884a
  host: localhost

production:
  <<: *default
  adapter: postgresql
  database: friendList
  username: root
  password: resa884a
  host: localhost
